import { Button, Typography, useTheme } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
 import styles from '../styles/Home.module.css'
 import { palette } from '@mui/system';
 

const Home: NextPage = () => {
  const theme = useTheme();
  return (
    <div className={styles.container}>
      <Head>
        <title>Streamer Match</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant='h1'>
          Welcome to <a href="https://nextjs.org"><span style={{color: theme.palette.secondary.light }}>Streamer</span><span style={{color: theme.palette.info.light }}> Match</span>!</a>
        </Typography>

        <Button color='success' className={styles.button} size='large' variant="contained">Get Started</Button>


        
       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
